version: '2'
services:

    web:
        image: nginx
        container_name: web-sppin
        volumes:
            - ./env/nginx/web.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/dist:/usr/share/nginx/html/
        ports:
            - "80:80"
        links:
            - proxy

    api-gateway:
        image: madsilver/ubuntu-nodejs:latest
        container_name: api-sppin
        command: npm run start
        volumes:
            - ./api-gateway/:/usr/app/
        ports:
            - "3000:3000"
        links:
            - ms-user
            - ms-module

    proxy:
        image: stepankuzmin/nginx-with-redis
        container_name: proxy-api
        volumes:
            - ./env/nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8080:8080"
        links:
            - api-gateway

    ms-user:
        image: madsilver/ubuntu-nodejs:latest
        container_name: ms-sppin-user
        command: npm run start
        volumes:
            - ./microservices/ms-user/:/usr/app/
        ports:
            - "3001:3001"
        links:
            - db

    ms-module:
        image: madsilver/ubuntu-nodejs:latest
        container_name: ms-sppin-module
        command: npm run start
        volumes:
            - ./microservices/ms-module/:/usr/app/
        ports:
            - "3002:3002"
        links:
            - db

    db:
        image: mysql:5.7
        container_name: db-sppin
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data/mysql:/var/lib/mysql
