version: '2'
services:
    ms-user:
        build: .
        image: silver/scs-user:latest
        container_name: ms-sppin-user
        command: npm run start
        volumes:
            - ./ms-user/:/usr/app/
        ports:
            - "3001:3001"
        links:
            - db
    ms-module:
        image: silver/scs-user:latest
        container_name: ms-sppin-module
        command: npm run start
        volumes:
            - ./ms-module/:/usr/app/
        ports:
            - "3002:3002"
        links:
            - db

    ms-log:
        image: silver/scs-user:latest
        container_name: ms-sppin-log
        command: npm run start
        volumes:
            - ./ms-log/:/usr/app/
        ports:
            - "3003:3003"
        links:
            - db

    db:
        image: mysql:5.7
        container_name: db-sppin
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
